"""village_pulse.archive — Multi-day historical report archive generator.

This module generates a browsable archive of daily Village Pulse reports,
producing one HTML dashboard per village day plus an index page that links
to every day.  It is designed to be called from the GitHub Pages workflow so
that the live site always contains the latest N days of history.

Typical use::

    from village_pulse import archive
    archive.generate_archive("./_site", days_back=30)

Or from the command line::

    python -m village_pulse.archive --days-back 30 --output ./_site
"""

from __future__ import annotations

import argparse

import logging
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Optional

from village_pulse import analytics, api_client, report

LOG = logging.getLogger(__name__)

DEFAULT_DAYS_BACK = 30


def _generate_index_page(
    reports: list[dict[str, Any]],
    output_dir: Path,
    *,
    generated_at: str,
    village_day: int,
) -> Path:
    """Write an index.html that links to every daily report."""

    rows = []
    for r in reports:
        day = r["day"]
        filename = r["filename"]
        total = r.get("total_events", 0)
        msgs = r.get("total_messages", 0)
        agents = r.get("unique_agents", 0)
        status_class = "good" if msgs > 0 else "muted"
        rows.append(
            f'<tr class="{status_class}">'
            f'<td><a href="{filename}">Day {day}</a></td>'
            f'<td>{msgs}</td>'
            f'<td>{total}</td>'
            f'<td>{agents}</td>'
            f'</tr>'
        )

    rows_html = "\n".join(rows)  # newest first

    html = f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Village Pulse Archive</title>
  <style>
    :root {{
      color-scheme: light;
      --bg: #f6f8fb;
      --panel: #ffffff;
      --ink: #172033;
      --muted: #64748b;
      --line: #d9e2ef;
      --accent: #2f6fed;
      --accent-soft: #e8f0ff;
      --good: #17803d;
      --shadow: 0 12px 28px rgba(23, 32, 51, 0.08);
    }}
    * {{ box-sizing: border-box; }}
    body {{
      margin: 0;
      font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
      background: radial-gradient(circle at top left, #e8f0ff 0, transparent 34rem), var(--bg);
      color: var(--ink);
      line-height: 1.5;
    }}
    header {{
      padding: 2.5rem clamp(1rem, 4vw, 4rem) 1.5rem;
      border-bottom: 1px solid var(--line);
      background: rgba(255, 255, 255, 0.78);
      backdrop-filter: blur(8px);
    }}
    h1 {{ margin: 0 0 .4rem; font-size: clamp(2rem, 4vw, 3.4rem); letter-spacing: -0.04em; }}
    .subtitle {{ color: var(--muted); max-width: 70rem; }}
    main {{ padding: 1.5rem clamp(1rem, 4vw, 4rem) 3rem; }}
    .meta {{ display: flex; flex-wrap: wrap; gap: .6rem; margin-top: 1rem; }}
    .pill {{
      display: inline-flex; align-items: center; gap: .3rem;
      border: 1px solid var(--line); background: var(--panel); color: var(--muted);
      border-radius: 999px; padding: .35rem .7rem; font-size: .9rem;
    }}
    table {{ width: 100%; border-collapse: collapse; font-size: .95rem; background: var(--panel); border: 1px solid var(--line); border-radius: 1rem; box-shadow: var(--shadow); }}
    th, td {{ padding: .65rem .55rem; border-bottom: 1px solid var(--line); text-align: left; }}
    th {{ color: var(--muted); font-size: .78rem; text-transform: uppercase; letter-spacing: .06em; background: #fbfdff; }}
    tr:last-child td {{ border-bottom: 0; }}
    a {{ color: var(--accent); text-decoration: none; }}
    a:hover {{ text-decoration: underline; }}
    .good {{ color: var(--good); font-weight: 650; }}
    .muted {{ color: var(--muted); }}
    footer {{ margin-top: 2rem; color: var(--muted); font-size: .9rem; }}
  </style>
</head>
<body>
  <header>
    <h1>Village Pulse Archive</h1>
    <p class="subtitle">Historical daily dashboards for AI Village activity.</p>
    <div class="meta">
      <span class="pill">Current village day: {village_day}</span>
      <span class="pill">Generated {generated_at}</span>
      <span class="pill">{len(reports)} days archived</span>
    </div>
  </header>
  <main>
    <table>
      <thead>
        <tr><th>Day</th><th>Messages</th><th>Total events</th><th>Active agents</th></tr>
      </thead>
      <tbody>
        {rows_html}
      </tbody>
    </table>
    <footer>Generated by Village Pulse. <a href="https://github.com/ai-village-agents/village-pulse">Source code</a></footer>
  </main>
</body>
</html>
"""
    index_path = output_dir / "index.html"
    index_path.write_text(html, encoding="utf-8")
    return index_path


def generate_archive(
    output_dir: str | Path,
    *,
    days_back: int = DEFAULT_DAYS_BACK,
    endpoint: str = api_client.DEFAULT_ENDPOINT,
    village_slug: str = api_client.DEFAULT_VILLAGE_SLUG,
    village_id: Optional[str] = None,
) -> list[dict[str, Any]]:
    """Generate one HTML report per village day and an index page.

    Args:
        output_dir: Directory to write reports into (created if missing).
        days_back: How many past village days to include.
        endpoint: Village API base URL.
        village_slug: Village slug for discovery.
        village_id: Optional pre-known village UUID.

    Returns:
        A list of metadata dicts, one per day, with keys ``day``,
        ``filename``, ``total_events``, ``total_messages``, ``unique_agents``.
    """
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)

    client = api_client.VillageAPIClient(
        endpoint=endpoint,
        village_slug=village_slug,
        village_id=village_id,
    )

    current_day = client._discover_latest_day()
    if current_day is None:
        LOG.warning("Could not discover current village day; falling back to days_back range")
        current_day = days_back

    reports: list[dict[str, Any]] = []

    for day in range(current_day, max(0, current_day - days_back), -1):
        LOG.info("Fetching day %d ...", day)
        try:
            raw_events = list(client.iter_raw_events_for_day(day))
        except api_client.APIError as exc:
            LOG.warning("API error for day %d: %s — skipping", day, exc)
            continue

        if not raw_events:
            LOG.info("Day %d has no events — skipping", day)
            continue

        # Flatten events using the same logic as fetch_events
        agents = client.get_agents()
        rooms = client.get_rooms()
        events = [
            api_client._flatten_event(raw, agents=agents, rooms=rooms)
            for raw in raw_events
        ]

        metrics = analytics.compute_all(events)
        meta = metrics.get("meta", {})

        filename = f"report_day{day}.html"
        day_path = output_path / filename

        report.generate(
            metrics,
            day_path,
            context={
                "days": 1,
                "version": "0.1.0",
                "title": f"Village Pulse — Day {day}",
            },
        )

        reports.append({
            "day": day,
            "filename": filename,
            "total_events": meta.get("total_events", 0),
            "total_messages": meta.get("total_messages", 0),
            "unique_agents": meta.get("unique_agents", 0),
        })
        LOG.info("Day %d → %s (%d events, %d messages)", day, filename, meta.get("total_events", 0), meta.get("total_messages", 0))

    # Also generate the combined "latest" report for convenience
    if reports:
        latest_day = reports[0]["day"]
        latest_report = output_path / f"report_day{latest_day}.html"
        latest_index = output_path / "report_latest.html"
        if latest_report.exists():
            latest_index.write_text(latest_report.read_text(encoding="utf-8"), encoding="utf-8")

    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    _generate_index_page(reports, output_path, generated_at=generated_at, village_day=current_day or 0)


    return reports


def main(argv: list[str] | None = None) -> int:
    """CLI entry point for the archive generator."""
    parser = argparse.ArgumentParser(description="Generate a multi-day Village Pulse archive.")
    parser.add_argument("--output", "-o", required=True, help="Output directory for HTML reports.")
    parser.add_argument("--days-back", "-d", type=int, default=DEFAULT_DAYS_BACK, help="Number of past days to archive (default: %(default)s).")
    parser.add_argument("--endpoint", default=api_client.DEFAULT_ENDPOINT, help="Village API endpoint.")
    parser.add_argument("--verbose", "-v", action="store_true", help="Enable debug logging.")
    args = parser.parse_args(argv)

    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(asctime)s %(levelname)s %(name)s: %(message)s",
    )

    try:
        reports = generate_archive(
            args.output,
            days_back=args.days_back,
            endpoint=args.endpoint,
        )
        print(f"Archive generated: {len(reports)} day reports in {args.output}")
        return 0
    except Exception as exc:
        LOG.exception("Archive generation failed: %s", exc)
        return 1


if __name__ == "__main__":
    sys.exit(main())
